graylog_server_version: "0.20.1"
graylog_server_prefix: "/usr/local"
graylog_server_dir: "#{graylog_server_prefix}/graylog2-server-#{graylog_server_version}"
graylog_server_pid_file: "/var/run/graylog-server.pid"
graylog_server_port: 12201
graylog_server_syslog_port: 12514

graylog_web_version: "0.20.1"
graylog_web_prefix: "/usr/local"
graylog_web_dir: "#{graylog_web_prefix}/graylog2-web-interface-#{graylog_web_version}"
graylog_web_pid_file: "/var/run/graylog-web.pid"
graylog_web_port: 9000

graylog_web_username: admin
graylog_web_password: admin1

graylog_mongo_database: graylog2
graylog_elasticsearch_index: "graylog2_#{Rubber.env}"

web_tools_proxies:
  graylog:
    role: graylog_web
    port: "#{graylog_web_port}"
    path: /

role_dependencies:
  graylog_server: [graylog_mongodb, graylog_elasticsearch]
  graylog_mongodb: [mongodb]
  graylog_elasticsearch: [elasticsearch]

roles:
  graylog_server:
    packages: [openjdk-7-jdk, mongodb-10gen]
  graylog_web:
    packages: [openjdk-7-jdk]

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_server_secret: 6d2a6e9b66095e8db71ff63f1ede8f0cd7481b0f9db5e43fe4f3cb5688b5d9f232ac0de41f56fb2c616359793092e7e0c5168a6be876d40e3a1506ca99699db1823fb98216d5a1d7a8effc4b4469bef66987d8098345b759fc9eb339f5195594

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_web_secret: 73209d81848302d85aada18a421e31b437a9dcbeef19ab3a180d33c87bce8170b58285024807ef867658963ed7bcff37b140848bf49d2888b72aa3f0bf5cb2f01a4c39f1e33b41c0b86a4cd5d926325a4af6d23f71b4ca92fb8ddde96bb9e93d
